/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package cn.questsoft.lazandroidormdemo;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int hidemenu=0x7f020000;
        public static final int home1=0x7f020001;
        public static final int home2=0x7f020002;
        public static final int ic_launcher=0x7f020003;
        public static final int mine1=0x7f020004;
        public static final int mine2=0x7f020005;
        public static final int returnmenu=0x7f020006;
        public static final int takephoto1=0x7f020007;
    }
    public static final class layout {
        public static final int activity_app=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int hello_world=0x7f040001;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f050000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f050001;
    }
}
